### ISSUE TITLE
`make test` failed

### ISSUE THREAD

**Issue by JesseAldridge** [limetext/backend#128]
macOS High Sierra
Version 10.13.3

```
$ make test
# github.com/limetext/backend
syntax_test.go:11:2: cannot find package "github.com/limetext/sublime/textmate/language" in any of:
	/usr/local/Cellar/go/1.9.3/libexec/src/github.com/limetext/sublime/textmate/language (from $GOROOT)
	/Users/jesse_aldridge/go/src/github.com/limetext/sublime/textmate/language (from $GOPATH)
FAIL	github.com/limetext/backend [setup failed]
ok  	github.com/limetext/backend/clipboard	1.100s [no tests to run]
ok  	github.com/limetext/backend/keys	1.084s
ok  	github.com/limetext/backend/log	1.089s
--- FAIL: TestWatch (0.32s)
panic: value of font_face cannot be represented as an string: "" [recovered]
	panic: value of font_face cannot be represented as an string: ""

goroutine 34 [running]:
testing.tRunner.func1(0xc42010c000)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:711 +0x5d9
panic(0x4233ee0, 0xc4200f22b0)
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/panic.go:491 +0x2a2
github.com/limetext/text.(*Settings).String(0xc420104090, 0x427942a, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jesse_aldridge/go/src/github.com/limetext/text/settings.go:167 +0x27c
github.com/limetext/backend/packages.TestWatch(0xc42010c000)
	/Users/jesse_aldridge/go/src/github.com/limetext/backend/packages/json_test.go:74 +0xb64
testing.tRunner(0xc42010c000, 0x4282b40)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:789 +0x569
FAIL	github.com/limetext/backend/packages	0.449s
ok  	github.com/limetext/backend/parser	1.030s [no tests to run]
ok  	github.com/limetext/backend/render	1.028s
==================
WARNING: DATA RACE
Write at 0x00c42010c593 by goroutine 41:
  github.com/limetext/backend/watch.(*dummy).done()
      /Users/jesse_aldridge/go/src/github.com/limetext/backend/watch/watcher_test.go:106 +0x104
  github.com/limetext/backend/watch.(*dummy).FileRemoved()
      /Users/jesse_aldridge/go/src/github.com/limetext/backend/watch/watcher_test.go:118 +0x57
  github.com/limetext/backend/watch.(*Watcher).apply()
      /Users/jesse_aldridge/go/src/github.com/limetext/backend/watch/watcher.go:307 +0x1d8
  github.com/limetext/backend/watch.(*Watcher).parseEv()
      /Users/jesse_aldridge/go/src/github.com/limetext/backend/watch/watcher.go:256 +0x19d
  github.com/limetext/backend/watch.(*Watcher).observe()
      /Users/jesse_aldridge/go/src/github.com/limetext/backend/watch/watcher.go:246 +0x48

Previous read at 0x00c42010c593 by goroutine 40:
  github.com/limetext/backend/watch.TestDeleteEvent()
      /Users/jesse_aldridge/go/src/github.com/limetext/backend/watch/watcher_test.go:377 +0x38a
  testing.tRunner()
      /usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:746 +0x16c

Goroutine 41 (running) created at:
  github.com/limetext/backend/watch.NewWatcher()
      /Users/jesse_aldridge/go/src/github.com/limetext/backend/watch/watcher.go:59 +0x281
  github.com/limetext/backend/watch.newWatcher()
      /Users/jesse_aldridge/go/src/github.com/limetext/backend/watch/watcher_test.go:17 +0x33
  github.com/limetext/backend/watch.TestDeleteEvent()
      /Users/jesse_aldridge/go/src/github.com/limetext/backend/watch/watcher_test.go:368 +0xa7
  testing.tRunner()
      /usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:746 +0x16c

Goroutine 40 (running) created at:
  testing.(*T).Run()
      /usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:921 +0x206
  main.main()
      github.com/limetext/backend/watch/_test/_testmain.go:70 +0x1d3
==================
--- FAIL: TestDeleteEvent (0.07s)
	testing.go:699: race detected during execution of test
FAIL
FAIL	github.com/limetext/backend/watch	0.305s
make: *** [test] Error 1
```

**Comment by zoli** [comment]
As you editted the building page for resolving this you should run `go get -v -u github.com/limetext/sublime`, but why is this hapenning? I think it's because we only use this package in tests.

This needs confirmation and a better fix.
